#!/bin/bash

# Tweet a cat fact in Yoda speak from the CLI

YCFCLI=~/nodejs-ycf/ycfcli.js
TWTBIN=/usr/bin/ttytter

if [ -f ${YCFCLI} ]; then
  #echo "DEBUG: found ${YCFCLI}"
  STATUS=`node ${YCFCLI}`
  CHARCT=`echo ${STATUS} | wc -m`
  #echo "DEBUG: found ${CHARCT} characters in message ==>"
  #echo "DEBUG: ${STATUS}"
  if [[ ${CHARCT} -gt 10 && ${CHARCT} -lt 140 ]]; then
    #echo "DEBUG: got a possible status between 10 and 140 chars"
    #echo "DEBUG: would run... ${TWTBIN} -ssl -status=\"${STATUS}\""
    ${TWTBIN} -ssl -status="${STATUS}" > /dev/null 2>&1
  fi
fi
